// import {Button} from "../../Components/Button/Button"
// const courses = [
//   {
//     id: 1,
//     image: "/course1.jpg",
//     tag: "Digital Marketing",
//     title: "Starting SEO As Your Home Based Business",
//     rating: 4.5,
//     students: 1200,
//     lessons: 12,
//     price: "$50.00",
//   },
//   {
//     id: 2,
//     image: "/course2.jpg",
//     tag: "UI/UX Design",
//     title: "User Experience Design Essentials",
//     rating: 4.8,
//     students: 980,
//     lessons: 18,
//     price: "$45.00",
//   },
//   {
//     id: 3,
//     image: "/course3.jpg",
//     tag: "Business",
//     title: "Business Strategy Fundamentals",
//     rating: 4.6,
//     students: 760,
//     lessons: 15,
//     price: "$60.00",
//   },
//   {
//     id: 4,
//     image: "/course4.jpg",
//     tag: "Development",
//     title: "Frontend Development With React",
//     rating: 4.9,
//     students: 1500,
//     lessons: 20,
//     price: "$55.00",
//   },
//   {
//     id: 5,
//     image: "/course5.jpg",
//     tag: "Graphic Design",
//     title: "Graphic Design Masterclass",
//     rating: 4.4,
//     students: 640,
//     lessons: 10,
//     price: "$40.00",
//   },
//   {
//     id: 6,
//     image: "/course6.jpg",
//     tag: "Photography",
//     title: "Photography From Beginner To Pro",
//     rating: 4.7,
//     students: 890,
//     lessons: 14,
//     price: "$48.00",
//   },
// ];
